eveseat/notifications

- src/Alerts/Corp/StarbaseSiphons.php
- src/Http/routes.php
A starbase may be empty and therefore, don't have a modules attribute according to https://github.com/eveseat/services/blob/master/src/Repositories/Corporation/Starbases.php#L191-L194
```
[2017-05-06 18:55:09] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function each() on null in /srv/dae-i.eveseat.net/vendor/eveseat/notifications/src/Alerts/Corp/StarbaseSiphons.php:75
#0 /srv/dae-i.eveseat.net/bootstrap/cache/compiled.php(12819): Seat\Notifications\Alerts\Corp\StarbaseSiphons->Seat\Notifications\Alerts\Corp\{closure}(Object(Seat\Eveapi\Models\Corporation\Starbase), 7)
#1 /srv/dae-i.eveseat.net/vendor/eveseat/notifications/src/Alerts/Corp/StarbaseSiphons.php(99): Illuminate\Support\Collection->each(Object(Closure))
#2 …
```
> Starbase Siphon alert hotfix

- src/NotificationsServiceProvider.php
This implement a SeAT specific Provider which have to be inherited by all SeAT package (including plugins) to return proper information and implement auto-discovery into a central place.
**Related to**: eveseat/web#258
**Depends**: eveseat/services#80
> feat(versions): Implement new version management for Notifications package

- src/Alerts/Corp/Killmails.php
due to our surrogate pattern, the each method is causing an exception
when it attempt to
sort records based on the primary key.
Closes eveseat/seat#551
> fix(notifications): enforce corporation killmails sorting

- src/Alerts/Corp/MemberTokenState.php
due to our surrogate pattern, the each method is causing an exception
when it attempt to sort records based on the primary key.
Closes eveseat/seat#552
> fix(notifications): enforce corporation member tracking sorting

- composer.json
- src/Alerts/Char/StructureUnderAttack.php
- src/Config/notifications.alerts.php
- src/Notifications/StructureUnderAttack.php
DEPENDENCIES eveseat/docker-eveseat-app#5 eveseat/docker-eveseat-worker#3 eveseat/scripts#28
Rendered this way under Slack
Rendered this way under Discord
> feat(notifications): add structure under attack support

- src/Alerts/Char/SovStructureDestroyed.php
- src/Config/notifications.alerts.php
- src/Notifications/AbstractNotification.php
- src/Notifications/SovStructureDestroyed.php
DEPENDENCIES: eveseat/notifications#26 eveseat/docker-eveseat-app#5 eveseat/docker-eveseat-worker#3 eveseat/scripts#28
> feat(notifications): add sovereignty structure destroyed support

- src/Alerts/Char/CorpAllBillMsg.php
- src/Config/notifications.alerts.php
- src/Notifications/CorpAllBillMsg.php
> feat(notifications): add corporation bill notification support

- src/Alerts/Char/StructureFuelAlert.php
- src/Config/notifications.alerts.php
- src/Notifications/StructureFuelAlert.php
> feat(notifications): add structure fuel notification support

- src/Alerts/Char/MoonMiningExtractionFinished.php
- src/Config/notifications.alerts.php
- src/Notifications/MoonMiningExtractionFinished.php
Slack rendering
Discord rendering
> feat(notifications): add moon mining extraction notification support

- src/Alerts/Char/StructureServicesOffline.php
- src/Config/notifications.alerts.php
- src/Notifications/StructureServicesOffline.php
Slack rendering
Discord rendering
> feat(notifications): add structure service offline notification support

- src/Alerts/Char/CharLeftCorpMsg.php
- src/Config/notifications.alerts.php
- src/Notifications/CharLeftCorpMsg.php
- src/Notifications/Killmail.php
> feat(notifications): add corporation character left notification support

- src/NotificationsServiceProvider.php
in order to keep consistency with packages, AbstractSeatPlugin is
moved to main package - as it will be extended by every single seat
packages (core and third party).
> refactor(core): move AbstractSeatPlugin from services to seat package

- .styleci.yml
this directive is non longer in Laravel preset.
> ci(styleci): remove length_ordered_imports

- src/NotificationsServiceProvider.php
Configuration related to notifications will now be available inside `SEAT_PATH/config/notifications.alerts.php` and a new tag will be available (`seat`) - allowing to publish certain part of the project.
This will avoid to use `php artisan vendor:publish --all` :)
Also, people will be able to customize their notification handler easier ;)
Special thanks to @wfjsw which point me to that workflow.
> feat: publish alerts configuration outside package

- src/Notifications/Contracts/Slack/ContractNotification.php
Since the PRs for contract notifications and rate limiting were merged at the same time, the contract notification wasn't adapted to the slack rate limiting. This PR fixes it.
> FIX: Use rate limiting for contracts

- src/Notifications/Corporations/Mail/CharLeftCorpMsg.php
- src/Notifications/Corporations/Slack/CharLeftCorpMsg.php
Currently, if the notifcation lacks some part of the information, all of the possible information is left blank. resulting in many notifcations that only say `A character has left corporation!` This attempts to fix that so that any information the notification has, will be posted instead of nothing.
> update corp leave message to allow corp or char info if either is known

- src/Observers/SquadApplicationObserver.php
"Squad Application" notifications are currently handled as if they are "New Squad Member" notifications while searching on which integration to send the notification on.
It looks like this was a copy&paste error. 
I think we should merge this into seat 4 too, since we have a real user on discord that is affected by this problem.
> fix squad application notification dispatching

- composer.json
- src/Config/notifications.alerts.php
- src/Notifications/Characters/Discord/RaffleCreated.php
- src/Notifications/Characters/Discord/RaffleExpired.php
- src/Notifications/Characters/Discord/RaffleFinished.php
- src/Notifications/Characters/Discord/ResearchMissionAvailableMsg.php
- src/Notifications/Characters/Discord/StoryLineMissionAvailableMsg.php
- src/Notifications/Contracts/Discord/ContractNotification.php
- src/Notifications/Seat/Discord/SquadApplicationNotification.php
- src/Notifications/Seat/Discord/SquadMemberNotification.php
- src/Notifications/Seat/Discord/SquadMemberRemovedNotification.php
- src/Notifications/Structures/Discord/AbstractDiscordMoonMiningExtraction.php
- src/Notifications/Structures/Discord/AllAnchoringMsg.php
- src/Notifications/Structures/Discord/MoonMiningExtractionFinished.php
- src/Notifications/Structures/Discord/MoonMiningExtractionStarted.php
- src/Notifications/Structures/Discord/OrbitalAttacked.php
- src/Notifications/Structures/Discord/OwnershipTransferred.php
- src/Notifications/Structures/Discord/StructureAnchoring.php
- src/Notifications/Structures/Discord/StructureDestroyed.php
- src/Notifications/Structures/Discord/StructureFuelAlert.php
- src/Notifications/Structures/Discord/StructureLostArmor.php
- src/Notifications/Structures/Discord/StructureLostShields.php
- src/Notifications/Structures/Discord/StructureServicesOffline.php
- src/Notifications/Structures/Discord/StructureUnanchoring.php
- src/Notifications/Structures/Discord/StructureUnderAttack.php
- src/Notifications/Structures/Discord/StructureWentHighPower.php
- src/Notifications/Structures/Discord/StructureWentLowPower.php
- src/Notifications/Structures/Slack/AbstractSlackMoonMiningExtraction.php
- src/Notifications/Structures/Traits/MoonMiningNotificationTrait.php
I took all Slack Notifications, copied and converted them into Discord Notifications where no Discord Notification existed before.
> Add missing discord notifications

- src/Config/notifications.integrations.php
- src/Http/Controllers/IntegrationsController.php
- src/NotificationsServiceProvider.php
- src/resources/views/integrations/list.blade.php
This PR allows plugins to register their own integration types so that they show up on the list of integration types when creating new integrations
> makelist of integration types dynamic

- src/Notifications/Sovereignties/Discord/SovStructureDestroyed.php
- src/Notifications/Sovereignties/Discord/SovStructureReinforced.php
- src/Notifications/Structures/Traits/MoonMiningNotificationTrait.php
- Moon Mining notifications on discord failed while the import of Seat\Eveapi\Models\Sde\InvType was missing.
- SOV notifications on discord failed while SolarSystem loaded and properties not match to MapDenormalize items used for slack notifications.
> Fix discord notifications

- src/Notifications/Sovereignties/Discord/EntosisCaptureStarted.php
- src/Notifications/Sovereignties/Discord/SovCommandNodeEventStarted.php
- src/Notifications/Structures/Traits/MoonMiningNotificationTrait.php
- [Fix colors for moon mining discord notifications.](https://github.com/eveseat/notifications/commit/ce8a7c9ed3259c8752b934cca7b072ee611ff83b)
- [SolarSystem issue while not used MapDenormalize](https://github.com/eveseat/notifications/commit/63136d5d79034fa05a761a9c5d02cc77c2e265e8)
> Fix discord messages again

- src/Config/notifications.alerts.php
- src/Notifications/Wars/Discord/AllWarDeclaredMsg.php
- src/Notifications/Wars/Discord/AllWarInvalidatedMsg.php
- src/Notifications/Wars/Discord/AllyJoinedWarAggressorMsg.php
- src/Notifications/Wars/Discord/AllyJoinedWarAllyMsg.php
- src/Notifications/Wars/Discord/AllyJoinedWarDefenderMsg.php
- src/Notifications/Wars/Discord/WarDeclaredMsg.php
- src/Notifications/Wars/Slack/WarDeclaredMsg.php
- src/resources/lang/en/alerts.php
V5 re-implementation of https://github.com/eveseat/notifications/pull/91
- Adds notification for the WarDeclared notification which is sent to Corporations when a war declaration is made.
- Fixes an issue that the notification fails if the attacker or defender does not exist in UniverseName yet.
If the UniverseName is not yet populated then the `category` property is null. Which makes the call to zKillBoardToDiscordLink fail with the error
```
zKillBoardToDiscordLink(): Argument #1 ($type) must be of type string, null given
```
> v5: Add Corporation Wardec notifications

- src/Notifications/Structures/Discord/StructureFuelAlert.php
Fix for the following error reported on discord:
```
TypeError: Seat\Notifications\Services\Discord\Messages\DiscordEmbed::color(): Argument #1 ($color) must be of type int, string given, called in /var/www/seat/vendor/eveseat/notifications/src/Notifications/Structures/Discord/StructureFuelAlert.php on line 90 and defined in /var/www/seat/vendor/eveseat/notifications/src/Services/Discord/Messages/DiscordEmbed.php:161
Stack trace:
#0 /var/www/seat/vendor/eveseat/notifications/src/Notifications/Structures/Discord/StructureFuelAlert.php(90): Seat\Notifications\Services\Discord\Messages\DiscordEmbed->color('#439fe0')
#1 /var/www/seat/vendor/eveseat/notifications/src/Services/Discord/Messages/DiscordMessage.php(226): Seat\Notifications\Notifications\Structures\Discord\StructureFuelAlert->Seat\N …
```
> Fix StructureFuelAlert color

- src/Notifications/Structures/Discord/OrbitalAttacked.php
- src/Notifications/Structures/Discord/StructureUnderAttack.php
fix: Fixed if Orbital attacker is missing alliance the Discord payload becomes invalid.
fix: Fixed StructureUnderAttack if missing Alliance
> fix: Fixed Orbital Discord Notification

- docs/notification-text-samples.md
- docs/notification-text-samples/StructureDestroyed.yaml
- docs/notification-text-samples/StructureLostShields.yaml
- docs/notification-text-samples/StructureUnderAttack-Armor.yaml
- docs/notification-text-samples/StructureUnderAttack-Hull.yaml
- docs/notification-text-samples/StructureUnderAttack-Shields.yaml
- docs/notification-text-samples/StructureWentLowPower.yaml
When working on notifications, it is, like with any code, important to test your changes.
This poses some unique challenges with the `notifications` packages: Some notifications
like `StructureDestroyed` are hard to generate in EVE for obvious reasons, meaning it is 
difficult to test them. This PR adds a few samples for structure notifications.
The data is randomized.
> Structure Notification Samples
